language: generic

sudo: required

services:
  -docker

before_install:
  -docker build -t pds17100/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  -docker run -e CI=true pds17100/react-test-app npm run test

after_success:
  -docker build -t pds17100/docker-frontend ./frontend
  -docker build -t pds17100/docker-backend ./backend
  -docker build -t pds17100/docker-nginx ./nginx

  -echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  -docker push pds17100/docker-frontend
  -docker push pds17100/docker-backend
  -docker push pds17100/docker-nginx
  